name: front_debits
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^8.0.7
  dio: ^5.8.0+1

  awidgets:
    git:
      url: https://gitlab.com/almeidatech/awidgets.git
      ref: main

dependency_overrides:
  awidgets:
    git:
      url: https://gitlab.com/almeidatech/awidgets.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true